version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "marcinkubica"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "marcinkubica"

  - package-ecosystem: "npm"
    directory: "/internal/frontend"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "marcinkubica"
