
# Server
bind: localhost
port: 8080
foreground: true
quiet: true

# don't open browser on startup
no-open: true

# UI behaviour
## do not allow to restart server via UI
# no-restart: true

## do not allow to delete files via UI
# no-delete: true

## do not allow to move files between groups via UI
# no-file-move: true

## shorthand for no-restart + no-delete + no-file-move
read-only: true

## do not auto-select newly added files in the browser
## prevents the UI from forcibly opening to new files when they are added
newfile-no-autoselect: true

## expose document links in the address bar
shareable: true

## use actual filenames in URLs instead of hash IDs (?filename=foo.md)
## falls back to hash ID if filenames are not unique within a group
true-filenames: true

## poll for file changes at this interval (e.g. 5s, 1m)
## useful for filesystems that don't support inotify events (e.g. network mounts)
## WARNING: do not use with GCS buckets - it will consume a lot of API quota and your wallet. Use Pub/Sub instead.
#poll-interval: 5s

# Groups
groups:
  - name: default
    watch:
      - ./**/*.md
 

