name: Make Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install --upgrade pip
        pip install -r .github/scripts/create-release/requirements.txt
        python .github/scripts/create-release/main.py



